# 3. Create pivot that will show Customers as rows, quarters as columns and Net Sales Amounts as Values as table valued function, parameter is Company ID

SELECT 
B.COMPANY_ID,
B.COMPANY_NAME,
A.CUSTOMER_ID,
B.CUSTOMER_NAME,

SUM(CASE WHEN YEAR_QUARTER IN ('2018Q1') THEN AMOUNT ELSE 0 END) AS Q1_2018,
SUM(CASE WHEN YEAR_QUARTER IN ('2018Q2') THEN AMOUNT ELSE 0 END) AS Q2_2018,
SUM(CASE WHEN YEAR_QUARTER IN ('2018Q3') THEN AMOUNT ELSE 0 END) AS Q3_2018,
SUM(CASE WHEN YEAR_QUARTER IN ('2018Q4') THEN AMOUNT ELSE 0 END) AS Q4_2018,
SUM(CASE WHEN YEAR_QUARTER IN ('2019Q1') THEN AMOUNT ELSE 0 END) AS Q1_2019,
SUM(CASE WHEN YEAR_QUARTER IN ('2019Q2') THEN AMOUNT ELSE 0 END) AS Q2_2019,
SUM(CASE WHEN YEAR_QUARTER IN ('2019Q3') THEN AMOUNT ELSE 0 END) AS Q3_2019,
SUM(CASE WHEN YEAR_QUARTER IN ('2019Q4') THEN AMOUNT ELSE 0 END) AS Q4_2019

FROM CUSTOMER_NETSALE AS A
LEFT JOIN (
SELECT CT.CUSTOMER_ID, CT.CUSTOMER_NAME, CT.COMPANY_ID, CO.COMPANY_NAME
FROM CUSTOMER AS CT
LEFT JOIN (SELECT * FROM COMPANY) AS CO
ON CT.COMPANY_ID = CO.COMPANY_ID
) AS B
ON A.CUSTOMER_ID = B.CUSTOMER_ID

GROUP BY
B.COMPANY_ID,
B.COMPANY_NAME,
A.CUSTOMER_ID,
B.CUSTOMER_NAME

ORDER BY
B.COMPANY_ID,
A.CUSTOMER_ID

