# 2. Make Selection that will show the Net Sales for Company ID 1

SELECT 
B.COMPANY_ID,
B.COMPANY_NAME,
A.CUSTOMER_ID,
B.CUSTOMER_NAME,
A.YEAR_QUARTER,
A.AMOUNT

FROM CUSTOMER_NETSALE AS A
LEFT JOIN (
SELECT CT.CUSTOMER_ID, CT.CUSTOMER_NAME, CT.COMPANY_ID, CO.COMPANY_NAME
FROM CUSTOMER AS CT
LEFT JOIN (SELECT * FROM COMPANY) AS CO
ON CT.COMPANY_ID = CO.COMPANY_ID
) AS B
ON A.CUSTOMER_ID = B.CUSTOMER_ID

WHERE B.COMPANY_ID IN (1)

GROUP BY
B.COMPANY_ID,
B.COMPANY_NAME,
A.CUSTOMER_ID,
B.CUSTOMER_NAME,
A.YEAR_QUARTER,
A.AMOUNT